frequency: 50
sensor_timeout: 0.1
two_d_mode: true
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

imu0: /ouster/imu
imu0_config: [false, false, false,
              true, true, true,
              true, true, true,
              false, false, false,
              false, false, false]
imu0_differential: false
imu0_relative: true
